name: Deploy Recipe Finder to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (workspace)
        run: npm ci

      - name: Build site (frontend only)
        env:
          NODE_ENV: production
          # optional override; otherwise api.ts auto-detects GH Pages and uses Render
          # VITE_API_BASE: https://recipegrind.onrender.com
        run: npm run -w apps/recipe-finder build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/recipe-finder/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
